# docker image based on miniconda image (debian:latest)
# ARG MINICONDA_DOCKER_VERSION
# FROM continuumio/miniconda3:${MINICONDA_DOCKER_VERSION}
FROM continuumio/miniconda3:23.10.0-1

# set the working dir to /usr/local/sen2like
WORKDIR /usr/local/sen2like

# Create the environment:
# copy environment.yml from sources to docker image
COPY ./environment.yml .
# create sen2like env from requirement
RUN conda env create --file environment.yml
